### ISSUE TITLE
issue with first or create

### ISSUE THREAD

**Issue by stefan694** [openscript/awesome_hstore_translate#4]
``` Record.where(param: "param 1").first_or_create ```
``` NoMethodError: undefined method `empty?' for nil:NilClass ```

I believe it is this line : 
``` if translations.has_key?(cur.to_s) && !translations[cur.to_s].empty? ```in instance_methods.rb
``` 
hash = {
  param_one: "param 1",
  param_two: "param 2"
}
hash.each do |param, title|
  record = Record.where(param: param.to_s)
  Record.create(param: param.to_s,   title_fr: title) unless record.present?
end

```

**Comment by openscript** [comment]
I've been looking into the issue and I can reproduce it with a test. Maybe you can work around the issue with `find_or_create_by()` until I've fixed it?

**Comment by sebweaver** [comment]
Hello,

I encounter the same issue and as @stefan694 said, the culprit is indeed this line:

`if translations.has_key?(cur.to_s) && !translations[cur.to_s].empty?`

This line only tests whether the translation exists and is not an empty string `''` but fails when the translation is `nil`.

In a first step replacing `empty?` by `blank?` would fix this case.

`if translations.has_key?(cur.to_s) && !translations[cur.to_s].blank?`

Which should even simplified as:

`if translations[cur.to_s].present?`

@openscript For now I have monkey-patched this method in my initializers, but I could release a PR pretty quickly if you want. I also fixed another blocking issue with `find_by`.

**Comment by openscript** [comment]
@sebweaver Sorry, for not responding recently. I was a few weeks hiking and I got ill last week. I'll check it out tomorrow and give you a proper feedback. Thank you for your effort and pull requests are always welcome.

**Comment by openscript** [comment]
Please see https://github.com/openscript/awesome_hstore_translate#limitations

Any idea how this could be fixed is welcome!
